/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.bibliotecario;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import sistemabibliotecario.*;

/**
 *
 * @author omar
 */
public class AlquilerIn extends javax.swing.JFrame implements ActionListener  {

  
    public AlquilerIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        usariofield = new javax.swing.JTextField();
        librofield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultadoarea = new javax.swing.JTextArea();
        jCheckBox2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Iniciar");
        jButton1.addActionListener(this);

        usariofield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usariofieldActionPerformed(evt);
            }
        });

        librofield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librofieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Código Usuario:");

        jLabel2.setText("Código de Libro");

        jLabel3.setText("Resultado");

        resultadoarea.setColumns(20);
        resultadoarea.setRows(5);
        jScrollPane1.setViewportView(resultadoarea);

        jCheckBox2.setText("Dia de Promocion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox2)
                    .addComponent(usariofield, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(librofield, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addComponent(usariofield, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addComponent(librofield, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jCheckBox2)
                .addGap(20, 20, 20)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        usariofield.getAccessibleContext().setAccessibleName("");
        usariofield.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usariofieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usariofieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usariofieldActionPerformed

    private void librofieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librofieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_librofieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlquilerIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlquilerIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlquilerIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlquilerIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlquilerIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField librofield;
    private javax.swing.JTextArea resultadoarea;
    private javax.swing.JTextField usariofield;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
     Alquiler alquiler = new Alquiler("25 - 01 - 2021", "pesos(MXN)", 20.00f);
     Alquiler promocion = new Alquiler("25 - 01 - 2021", "pesos(MXN)", 10.00f);
     
     Registro usuario = new Registro("5586423579", "TORR0022HMCYRDA8", true, "TO82", "Saul", "Torres", "Beberly Hills"); 
     Registro usuario2 = new Registro("5556782439", "JEVS9530HMCYRDA4", true, "JE56", "Pablo", "Ramírez", "Huston");
     Registro usuario3 = new Registro("5542875301", "SBSK0022HMCYRDA5", true, "SB63", "Kesto", "Hernández", "Verdansk");
        
     Tesis tesis = new Tesis(1, 1, "2025", "Omar Gutiérrez", "Juegos neuronales", 586423, "Ciencia", "Físico matemáticas");
     Tesis tesis2 = new Tesis(1, 1, "2025", "Ernesto Sánchez", "Búsqueda sensorial", 984565, "Tecnología", "Físico matemáticas");
     Tesis tesis3 = new Tesis(1, 1, "2025", "Edward Reyes", "POO for dumies", 586421, "Ciencia", "Físico matemáticas");
     
     Comics comic = new Comics(1, 2, "2000", "Stan Lee", "The Amazing Spiderman", 123852, "Marvel", "Spiderman");
     Comics comic2 = new Comics(1, 2, "2005", "Steve Divco", "Spectacular Spiderman", 125542, "Marvel", "Spiderman");
     Comics comic3 = new Comics(1, 2, "2010", "Frank Miller", "Batman Adventures", 654891, "DC", "Batman");
     
     Literatura literatura = new Literatura(1, 3, "2003", "Susan Collins", "El gremio de los magos", 568736, "Novela");
     Literatura literatura2 = new Literatura(1, 3, "2007", "Frank Kafka", "Metamorfosis", 987521, "Novela");
     Literatura literatura3 = new Literatura(1, 3, "1980", "Carl Sagan", "Cosmos", 124563, "Ciencia");
     
     Enciclopedia enciclopedia = new Enciclopedia(2, 1, "2009", "Curtis", "Curtis Biologia", 619898, "Biologia");
     Enciclopedia enciclopedia2 = new Enciclopedia(2, 2, "2014", "Stephen Hawking", "Breve historia en el tiempo", 75682, "Astrologia");
     Enciclopedia enciclopedia3 = new Enciclopedia(2, 3, "2018", "McGraw-Hill", "Medicina Interna", 846523, "Medicina");
     
     Biografia biografia = new Biografia("21 de Marzo de 1872", 2, 2, "1950", "Hemeregildo Reyes", "Benito Juárez",18436);
     Biografia biografia2 = new Biografia("17 de febrero", 2, 2, "1968","Pablo Marinus", "Gustavo Adolfo Bequer", 194560);
     Biografia biografia3 = new Biografia("20 de abril de 1889", 2, 2, "1955", "Pepe pecas", "Adolf Hitler", 536476);
     
     Tesis[] arrayTesis = {tesis, tesis2, tesis3};
     Comics[] arrayComics = {comic, comic2, comic3};
     Literatura[] arrayLiteratura = {literatura, literatura2, literatura3};
     Enciclopedia[] arrayEnciclopedia = {enciclopedia, enciclopedia2, enciclopedia3};
     Biografia[] arrayBiografia = {biografia, biografia2, biografia3};
     Registro[] arrayRegistro = {usuario, usuario2, usuario3};
     
        int codigo = 0;
        int i = 0, j = 0;
        boolean encontrar = false;
        String IDU = "";
        
        if(e.getSource()== jButton1){
            codigo = Integer.parseInt(librofield.getText());
            IDU = usariofield.getText();
            
            for(i = 0; i < 3; i++) {
                if(IDU.equals(arrayRegistro[i].getID())) {
                    for (j = 0; j < 3; j++) {
                        if(codigo == arrayTesis[j].getID()) {
                            encontrar = true;
                            if(jCheckBox2.isSelected())
                                resultadoarea.setText("Es prestado al usario: " + arrayRegistro[i].getNombre() + " " + arrayRegistro[i].getApellido() + 
                                        "\nEstatus: " + arrayRegistro[i].Vigencia(true) + 
                                        "\nLibro: " + arrayTesis[j].getTitulo() +
                                        "\nTarifa " + promocion.getPrecio() + " " + promocion.getDivisa());
                            else 
                                resultadoarea.setText("Es prestado al usario: " + arrayRegistro[i].getNombre() + " " + arrayRegistro[i].getApellido() +
                                        "\nEstatus: " + arrayRegistro[i].Vigencia(true) +
                                        "\nLibro: " + arrayTesis[j].getTitulo() +
                                        "\nTarifa: " + alquiler.getPrecio() + " " + alquiler.getDivisa());
                        }
                    }
                    for (j = 0; j < 3; j++) {
                        if(codigo == arrayComics[j].getID()) {
                            encontrar = true;
                            if(jCheckBox2.isSelected())
                                resultadoarea.setText("Es prestado al usario: " + arrayRegistro[i].getNombre() + " " + arrayRegistro[i].getApellido() + 
                                        "\nEstatus: " + arrayRegistro[i].Vigencia(false) + 
                                        "\nLibro: " + arrayComics[j].getTitulo() +
                                        "\nTarifa " + promocion.getPrecio() + " " + promocion.getDivisa());
                            else 
                                resultadoarea.setText("Es prestado al usario: " + arrayRegistro[i].getNombre() + " " + arrayRegistro[i].getApellido() +
                                        "\nEstatus: " + arrayRegistro[i].Vigencia(false) +
                                        "\nLibro: " + arrayComics[j].getTitulo() +
                                        "\nTarifa: " + alquiler.getPrecio() + " " + alquiler.getDivisa());
                        }
                    }
                    for (j = 0; j < 3; j++) {
                        if(codigo == arrayLiteratura[j].getID()) {
                            encontrar = true;
                            if(jCheckBox2.isSelected())
                                resultadoarea.setText("Es prestado al usario: " + arrayRegistro[i].getNombre() + " " + arrayRegistro[i].getApellido() + 
                                        "\nEstatus: " + arrayRegistro[i].Vigencia(false) + 
                                        "\nLibro: " + arrayLiteratura[j].getTitulo() +
                                        "\nTarifa " + promocion.getPrecio() + " " + promocion.getDivisa());
                            else 
                                resultadoarea.setText("Es prestado al usario: " + arrayRegistro[i].getNombre() + " " + arrayRegistro[i].getApellido() +
                                        "\nEstatus: " + arrayRegistro[i].Vigencia(false) +
                                        "\nLibro: " + arrayLiteratura[j].getTitulo() +
                                        "\nTarifa: " + alquiler.getPrecio() + " " + alquiler.getDivisa());
                        }
                    }
                    for (j = 0; j < 3; j++) {
                        if(codigo == arrayEnciclopedia[j].getID()) {
                            encontrar = true;
                            if(jCheckBox2.isSelected())
                                resultadoarea.setText("Es prestado al usario: " + arrayRegistro[i].getNombre() + " " + arrayRegistro[i].getApellido() + 
                                        "\nEstatus: " + arrayRegistro[i].Vigencia(true) + 
                                        "\nLibro: " + arrayEnciclopedia[j].getTitulo() +
                                        "\nTarifa " + promocion.getPrecio() + " " + promocion.getDivisa());
                            else 
                                resultadoarea.setText("Es prestado al usario: " + arrayRegistro[i].getNombre() + " " + arrayRegistro[i].getApellido() +
                                        "\nEstatus: " + arrayRegistro[i].Vigencia(true) +
                                        "\nLibro: " + arrayEnciclopedia[j].getTitulo() +
                                        "\nTarifa: " + alquiler.getPrecio() + " " + alquiler.getDivisa());
                        }
                    }
                    for (j = 0; j < 3; j++) {
                        if(codigo == arrayBiografia[j].getID()) {
                            encontrar = true;
                            if(jCheckBox2.isSelected())
                                resultadoarea.setText("Es prestado al usario: " + arrayRegistro[i].getNombre() + " " + arrayRegistro[i].getApellido() + 
                                        "\nEstatus: " + arrayRegistro[i].Vigencia(true) + 
                                        "\nLibro: " + arrayBiografia[j].getTitulo() +
                                        "\nTarifa " + promocion.getPrecio() + " " + promocion.getDivisa());
                            else 
                                resultadoarea.setText("Es prestado al usario: " + arrayRegistro[i].getNombre() + " " + arrayRegistro[i].getApellido() +
                                        "\nEstatus: " + arrayRegistro[i].Vigencia(true) +
                                        "\nLibro: " + arrayBiografia[j].getTitulo() +
                                        "\nTarifa: " + alquiler.getPrecio() + " " + alquiler.getDivisa());
                        }
                    }
                }
            }
            
            if(encontrar == false)
                resultadoarea.setText("Código no encontrado,\npor favor revise el código\ne inténtelo nuevamente");
        }
    }
}
