/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.bibliotecario;


import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import sistemabibliotecario.*;

/**
 *
 * @author omar
 */
public class LibrosInterfaz extends javax.swing.JFrame implements ItemListener{

    /**
     * Creates new form LibrosInterfaz
     */
    public LibrosInterfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Libros");
        setResizable(false);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel1.setText("Busqueda por:");

        jLabel2.setText("Resultado");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LIBRO", "AUTOR", "AÑO", "CODIGO" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
     Tesis tesis = new Tesis(1, 1, "2025", "Omar Gutiérrez", "Juegos neuronales", 586423, "Ciencia", "Físico matemáticas");
     Tesis tesis2 = new Tesis(1, 1, "2025", "Ernesto Sánchez", "Búsqueda sensorial", 984565, "Tecnología", "Físico matemáticas");
     Tesis tesis3 = new Tesis(1, 1, "2025", "Edward Reyes", "POO for dumies", 586421, "Ciencia", "Físico matemáticas");
     
     Comics comic = new Comics(1, 2, "2000", "Stan Lee", "The Amazing Spiderman", 123852, "Marvel", "Spiderman");
     Comics comic2 = new Comics(1, 2, "2005", "Steve Divco", "Spectacular Spiderman", 125542, "Marvel", "Spiderman");
     Comics comic3 = new Comics(1, 2, "2010", "Frank Miller", "Batman Adventures", 654891, "DC", "Batman");
     
     Literatura literatura = new Literatura(1, 3, "2003", "Susan Collins", "El gremio de los magos", 568736, "Novela");
     Literatura literatura2 = new Literatura(1, 3, "2007", "Frank Kafka", "Metamorfosis", 987521, "Novela");
     Literatura literatura3 = new Literatura(1, 3, "1980", "Carl Sagan", "Cosmos", 124563, "Ciencia");
     
     Enciclopedia enciclopedia = new Enciclopedia(2, 1, "2009", "Curtis", "Curtis Biologia", 619898, "Biologia");
     Enciclopedia enciclopedia2 = new Enciclopedia(2, 2, "2014", "Stephen Hawking", "Breve historia en el tiempo", 75682, "Astrologia");
     Enciclopedia enciclopedia3 = new Enciclopedia(2, 3, "2018", "McGraw-Hill", "Medicina Interna", 846523, "Medicina");
     
     Biografia biografia = new Biografia("21 de Marzo de 1872", 2, 2, "1950", "Hemeregildo Reyes", "Benito Juárez",18436);
     Biografia biografia2 = new Biografia("17 de febrero", 2, 2, "1968","Pablo Marinus", "Gustavo Adolfo Bequer", 194560);
     Biografia biografia3 = new Biografia("20 de abril de 1889", 2, 2, "1955", "Pepe pecas", "Adolf Hitler", 536476);
     
     Tesis[] arrayTesis = {tesis, tesis2, tesis3};
     Comics[] arrayComics = {comic, comic2, comic3};
     Literatura[] arrayLiteratura = {literatura, literatura2, literatura3};
     Enciclopedia[] arrayEnciclopedia = {enciclopedia, enciclopedia2, enciclopedia3};
     Biografia[] arrayBiografia = {biografia, biografia2, biografia3};
        
     String aux=jComboBox1.getSelectedItem().toString();
     String mostrarLibros = "";
     int i = 0;
     if(aux.equals("LIBRO")){
         String libro = jTextArea1.getText();
        jTextArea2.setText("Busqueda por LIBRO");
        for (i = 0; i < 3; i++) {
            if(libro.equals(arrayTesis[i].getTitulo())) {
                mostrarLibros += arrayTesis[i].mostrar() + "------------------------------------\n";
            }
        }
        for (i = 0; i < 3; i++) {
            if(libro.equals(arrayComics[i].getTitulo())) {
                mostrarLibros += arrayComics[i].mostrar() + "------------------------------------\n";
            }
        }
        for (i = 0; i < 3; i++) {
            if(libro.equals(arrayLiteratura[i].getTitulo())) {
                mostrarLibros += arrayLiteratura[i].mostrar() + "------------------------------------\n";
            }
        }
        for (i = 0; i < 3; i++) {
            if(libro.equals(arrayEnciclopedia[i].getTitulo())) {
                mostrarLibros += arrayEnciclopedia[i].mostrar() + "------------------------------------\n";
            }
        }
        for (i = 0; i < 3; i++) {
            if(libro.equals(arrayBiografia[i].getTitulo())) {
                mostrarLibros += arrayBiografia[i].mostrar() + "------------------------------------\n";
            }
        }
        jTextArea2.setText(mostrarLibros);
     }
     if(aux.equals("AUTOR")){
         String autor = jTextArea1.getText();
        jTextArea2.setText("Busqueda por AUTOR");
        for (i = 0; i < 3; i++) {
            if(autor.equals(arrayTesis[i].getAutor())) {
                mostrarLibros += arrayTesis[i].mostrar() + "------------------------------------\n";
            }
        }
        for (i = 0; i < 3; i++) {
            if(autor.equals(arrayComics[i].getAutor())) {
                mostrarLibros += arrayComics[i].mostrar() + "------------------------------------\n";
            }
        }
        for (i = 0; i < 3; i++) {
            if(autor.equals(arrayLiteratura[i].getAutor())) {
                mostrarLibros += arrayLiteratura[i].mostrar() + "------------------------------------\n";
            }
        }
        for (i = 0; i < 3; i++) {
            if(autor.equals(arrayEnciclopedia[i].getAutor())) {
                mostrarLibros += arrayEnciclopedia[i].mostrar() + "------------------------------------\n";
            }
        }
        for (i = 0; i < 3; i++) {
            if(autor.equals(arrayBiografia[i].getAutor())) {
                mostrarLibros += arrayBiografia[i].mostrar() + "------------------------------------\n";
            }
        }
        jTextArea2.setText(mostrarLibros);
     }
     if(aux.equals("AÑO")){
         String año = jTextArea1.getText();
        jTextArea2.setText("Busqueda por AÑO");
        for (i = 0; i < 3; i++) {
            if(año.equals(arrayTesis[i].getAnio())) {
                mostrarLibros += arrayTesis[i].mostrar() + "------------------------------------\n";
            }
        }
        for (i = 0; i < 3; i++) {
            if(año.equals(arrayComics[i].getAnio())) {
                mostrarLibros += arrayComics[i].mostrar() + "------------------------------------\n";
            }
        }
        for (i = 0; i < 3; i++) {
            if(año.equals(arrayLiteratura[i].getAnio())) {
                mostrarLibros += arrayLiteratura[i].mostrar() + "------------------------------------\n";
            }
        }
        for (i = 0; i < 3; i++) {
            if(año.equals(arrayEnciclopedia[i].getAnio())) {
                mostrarLibros += arrayEnciclopedia[i].mostrar() + "------------------------------------\n";
            }
        }
        for (i = 0; i < 3; i++) {
            if(año.equals(arrayBiografia[i].getAnio())) {
                mostrarLibros += arrayBiografia[i].mostrar() + "------------------------------------\n";
            }
        }
        jTextArea2.setText(mostrarLibros);
     }
     if(aux.equals("CODIGO")){
         String codigo = jTextArea1.getText();
        jTextArea2.setText("Busqueda por CODIGO");
        for (i = 0; i < 3; i++) {
            if(codigo.equals(String.valueOf(arrayTesis[i].getID()))) {
                mostrarLibros += arrayTesis[i].mostrar() + "------------------------------------\n";
            }
        }
        for (i = 0; i < 3; i++) {
            if(codigo.equals(String.valueOf(arrayComics[i].getID()))) {
                mostrarLibros += arrayComics[i].mostrar() + "------------------------------------\n";
            }
        }
        for (i = 0; i < 3; i++) {
            if(codigo.equals(String.valueOf(arrayLiteratura[i].getID()))) {
                mostrarLibros += arrayLiteratura[i].mostrar() + "------------------------------------\n";
            }
        }
        for (i = 0; i < 3; i++) {
            if(codigo.equals(String.valueOf(arrayEnciclopedia[i].getID()))) {
                mostrarLibros += arrayEnciclopedia[i].mostrar() + "------------------------------------\n";
            }
        }
        for (i = 0; i < 3; i++) {
            if(codigo.equals(String.valueOf(arrayBiografia[i].getID()))) {
                mostrarLibros += arrayBiografia[i].mostrar() + "------------------------------------\n";
            }
        }
        jTextArea2.setText(mostrarLibros);
     }     
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void itemStateChanged(ItemEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
